name: Build

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: 🔧 Create build
        run: |
          corepack enable
          yarn install
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build/*
          path: |
            build
          retention-days: 7
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

