name: Deploy to host server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: 🔧 Create build
        run: |
          corepack enable
          yarn install
          npm run build
      - name: 🚀 Deploy
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          rsync -r --delete -e "ssh -p 2222 -o StrictHostKeyChecking=no" ./build/ ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }}:${{ secrets.HOST_TARGET_DIR }}
